name: Test installing plugins

on: [push]

jobs:

  changed-files:
    runs-on: ubuntu-latest
    name: Get Changed files

    outputs:
      files: ${{ steps.getfile.outputs.files }}

    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: get changed files
        id: getfile
        run: |
          echo "::set-output name=files::$(git diff origin/master... --name-only | xargs)"

  test-install:
    runs-on: macos-latest
    name: Test FreeBSD job

    steps:
      - name: Test in FreeBSD
        id: test
        uses: vmactions/freebsd-vm@v0.1.2
        with:
          usesh: true
          prepare: |
            pkg update
            pkg install jq
          run: |
            freebsd-version

            for i in ${{ needs.changed-files.outputs.files }}
            do
                release=$(jq '.release' $i)
                if [[ $a == "12.2"* ]]
                then
                  echo "Testing install plugin pkgs from $i"
                fi
            done

