name: Test installing plugins

on: [push]

jobs:
  test-install:
    runs-on: macos-latest
    name: Test install updated plugins

    steps:
      - uses: actions/checkout@v2

      - name: get changed plugin files
        id: changed_plugins
        run: |
          plugin_files=$(git diff origin/master... --name-only | grep .json)
          echo $plugin_files
          echo "::set-output name=files::${plugin_files}"

      - name: Test in FreeBSD
        id: test
        uses: vmactions/freebsd-vm@v0.1.2
        with:
          usesh: true
          prepare: |
            pkg update
            pkg install -y jq
          run: |
            ls -l
            freebsd-version

            for plugin_file in ${{ steps.changed_plugins.outputs.files }}
            do
                release=$(jq '.release' $plugin_file)
                name=$(jq '.name' $plugin_file)

                if [ "$release" = "12.2-RELEASE" ]
                then
                  echo "Testing install plugin pkgs for plugin $name"

                  pkgs=$(jq '.pkgs[]' $plugin_file)
                  echo "Installing $name pkgs: $pkgs"
                  pkg install -y $pkgs
                else
                  echo "Plugin: $name has a release: $release older than latest FreeBSD version"
                fi
            done

