name: Test installing plugins

on: [push]

jobs:

  changed-files:
    runs-on: ubuntu-latest
    name: Get Changed files

    outputs:
      files: ${{ steps.getfiles.outputs.files }}

    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: get changed files
        id: getfiles
        run: |
          plugin_files=$(git diff origin/master... --name-only | grep .json)
          echo $plugin_files
          echo "::set-output name=files::${plugin_files}"

  test-install:
    runs-on: macos-latest
    name: Test install updated plugins
    needs: changed-files

    steps:
      - uses: actions/checkout@v2
      - name: Test in FreeBSD
        id: test
        uses: vmactions/freebsd-vm@v0.1.2
        with:
          usesh: true
          prepare: |
            pkg update
            pkg install -y jq
          run: |
            ls -l
            freebsd-version

            for i in ${{ needs.changed-files.outputs.files }}
            do
                release=$(jq '.release' $i)
                if [[ $a == "12.2"* ]]
                then
                  echo "Testing install plugin pkgs from $i"

                  pkgs=$(jq '.pkgs[]' $i)
                  echo "$i pkgs: $pkgs"
                  pkg install -y $pkgs
                fi
            done

