name: Test installing plugins

on: [push]

jobs:

  changes:
    runs-on: ubuntu-latest
    name: Get Changed files

    outputs:
      files: ${{ steps.getfiles.outputs.files }}

    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: get changed files
        id: getfiles
        run: |
          echo "::set-output name=files::$(git diff origin/master... --name-only | grep .json)"

  test-install:
    runs-on: macos-latest
    name: Test FreeBSD job

    steps:
      - name: Test in FreeBSD
        id: test
        uses: vmactions/freebsd-vm@v0.1.2
        with:
          usesh: true
          prepare: |
            pkg update
            pkg install -y jq
          run: |
            freebsd-version

            for i in ${{ needs.changes.outputs.files }}
            do
                release=$(jq '.release' $i)
                if [[ $a == "12.2"* ]]
                then
                  echo "Testing install plugin pkgs from $i"

                  pkgs=$(jq '.pkgs[]' $i)
                  echo "$i pkgs: $pkgs"
                  pkg install -y $pkgs
                fi
            done

